# Generated by Django 4.2.6 on 2023-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
