# Generated by Django 4.2.6 on 2024-01-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.application'),
        ),
    ]
