# Generated by Django 4.1.3 on 2023-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_user_role_alter_joblisting_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'employer'), ('job_seeker', 'job seeker')], default='employer', max_length=50),
        ),
    ]
