# Generated by Django 4.2.6 on 2024-01-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_status_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.status'),
            preserve_default=False,
        ),
    ]
